TARGET = helloStr charPointerOperation strcatExample filePointer fileDescriptor dynamicAllocation charAddress unionExample enumExample

all : ${TARGET}

helloStr : $@
charPointerOperation : $@
strcatExample : $@
filePointer : $@
fileDescriptor : $@
dynamicAllocation : $@
charAddress : $@
unionExample : $@
enumExample : $@

clean :
	rm ${TARGET}
