TARGET = helloStr charPointerOperation strcatExample filePointer fileDescriptor

all : ${TARGET}

helloStr : $@
charPointerOperation : $@
strcatExample : $@
filePointer : $@
fileDescriptor : $@

clean :
	rm ${TARGET}
