TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle arithmetics increment literal genderRatio

all : ${TARGET}

infinit : infinit.c
	cc -o infinit infinit.c

limit : $@
celsius2fahr : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
arithmetics : $@
increment : $@
literal : $@
genderRatio : $@

clean :
	rm ${TARGET}
