TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle arithmetics increment literal genderRatio compare compare2 sizeof oddeven fourBits fourBits2

all : ${TARGET}

infinit : infinit.c
	cc -o infinit infinit.c

limit : $@
celsius2fahr : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
arithmetics : $@
increment : $@
literal : $@
genderRatio : $@
compare : $@
compare2 : $@
sizeof : $@
oddeven : $@
fourBits : $@
fourBits2 : $@

clean :
	rm ${TARGET}
