TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigLetter one2Ten one2TenSum multiplyTable ascii star one2TenWhile one2TenDoWhile randomTwoInt staticLocalVarialbe functionSum returnValue power

all : ${TARGET}

lottoNumber : $@
absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2TenSum : $@
multiplyTable : $@
ascii : $@
star : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoInt : $@
staticLocalVarialbe : $@
functionSum : $@
returnValue : $@
power : $@

clean :
	rm ${TARGET}
